# -*- coding: utf-8 -*-
"""Article classificator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12m7FN8K97lyNRVvxPRanFPRQwCvcnAna
"""

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as Pd

df= Pd.read_csv("training_data.csv")
df=df[0:20][0:20]
bodyarr=df['body']
titlearr=df['title']

analyser=SentimentIntensityAnalyzer()

weightTitle=0.5
weightBody=0.5
negative=[]
positive=[]
neutral=[]

for i in range(len(titlearr)):
  title=titlearr[i]
  body=bodyarr[i]
  title_score=analyser.polarity_scores(title)
  body_score=analyser.polarity_scores(body)
  
  negative.append(title_score['neg']*weightTitle+body_score['neg']*weightBody)
  positive.append(title_score['pos']*weightTitle+body_score['pos']*weightBody)
  neutral.append(title_score['neu']*weightTitle+body_score['neu']*weightBody)
  

df["Negative"]=negative
df["Neutral"]=neutral
df['Positive']=positive
dfstat=Pd.DataFrame()
dfstat["Statistics"]=["avgNeg","avgNeu","avgPos","maxNeg","maxNeu","maxPos"]
avgNeg=sum(df["Negative"])/i
avgPos=sum(df["Positive"])/i
avgNeu=sum(df["Neutral"])/i
maxNeg=max(df["Negative"])
maxPos=max(df["Positive"])
maxNeu=max(df["Neutral"])
dfstat["Values"]=[avgNeg,avgNeu,avgPos,maxNeg,maxNeu,maxPos]

print(avgNeg,avgNeu,avgPos,maxNeg,maxNeu,maxPos)
print(df)

df.to_excel("Scores.xlsx")
dfstat.to_excel("Stats.xlsx")
